# KallistiOS ##version##
#
# arch/dreamcast Makefile
# (c)2001 Dan Potter
#   
# Makefile,v 1.3 2002/02/24 17:13:18 bardtx Exp
	
SUBDIRS=fs hardware kernel math sound util

include $(KOS_BASE)/Makefile.rules

all: subdirs
clean: clean_subdirs
