# KallistiOS ##version##
#
# kernel/fs/Makefile
# (c)2000-2001 Dan Potter
#   
# Makefile,v 1.1.1.1 2001/09/26 07:05:10 bardtx Exp

OBJS = fs.o fs_builtin.o fs_romdisk.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab

