# KallistiOS ##version##
#
# addons/Makefile
# (c)2000-2001 Dan Potter
#   
# Makefile,v 1.6 2002/02/13 05:46:09 bardtx Exp

all: build-zlib

clean:
	$(KOS_MAKE) -C zlib clean

build-zlib:
	$(KOS_MAKE) -C zlib

