# KallistiOS ##version##
#
# arch/dreamcast/fs/Makefile
# (c)2001 Dan Potter
#   
# Makefile,v 1.1.1.1 2001/09/26 07:05:11 bardtx Exp

# Dreamcast-specific file systems

OBJS = fs_iso9660.o fs_vmu.o fs_dcload.o dcload-syscall.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab



