# KallistiOS ##version##
#
# thread/Makefile
# (c)2001 Dan Potter
#   
# Makefile,v 1.1.1.1 2001/09/26 07:05:13 bardtx Exp

#OBJS = cond.o msg.o sem.o thread.o
OBJS =  sem.o cond.o
OBJS += thread.o thread_vars.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab



