# KallistiOS ##version##
#
# arch/dreamcast/util/Makefile
# (c)2001 Dan Potter
#   
# Makefile,v 1.1 2002/02/24 06:18:17 bardtx Exp


OBJS = vmu_pkg.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab


