# KallistiOS ##version##
#
# arch/dreamcast/math/Makefile
# (c)2001 Dan Potter
#   
# Makefile,v 1.1.1.1 2001/09/26 07:05:11 bardtx Exp

# Dreamcast-specific math functions

OBJS = fmath.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab


